// * This is a mock api with no actual backend nor database
// * I might make a separate backend for this in the future,
// * but for now i'll just use this fake data.

import type { Category, Filters, Article } from "../types/items";

const data: Article[] = [
	{
		id: 1,
		name: "RTX 4080 Super GPU",
		desc: "High-performance graphics card with 16GB GDDR6X memory for 4K gaming.",
		price: 1299.99,
		stock: 8,
		category: "parts",
		img: "",
	},
	{
		id: 2,
		name: "Ryzen 9 7950X Processor",
		desc: "16-core, 32-thread CPU optimized for gaming and heavy workloads.",
		price: 699.99,
		stock: 15,
		category: "parts",
		img: "",
	},
	{
		id: 3,
		name: "Corsair Vengeance 32GB DDR5 RAM",
		desc: "Dual-channel DDR5 memory kit running at 6000MHz.",
		price: 189.99,
		stock: 25,
		category: "parts",
		img: "",
	},
	{
		id: 4,
		name: "Samsung 990 Pro 2TB NVMe SSD",
		desc: "Ultra-fast PCIe 4.0 SSD for lightning-quick load times and file transfers.",
		price: 239.99,
		stock: 30,
		category: "parts",
		img: "",
	},
	{
		id: 5,
		name: "NZXT H7 Flow Case",
		desc: "Mid-tower ATX case with optimized airflow and tempered glass side panel.",
		price: 149.99,
		stock: 12,
		category: "cases",
		img: "",
	},
	{
		id: 6,
		name: "Lian Li O11 Dynamic EVO",
		desc: "Premium modular case with dual-chamber design and RGB lighting support.",
		price: 179.99,
		stock: 10,
		category: "cases",
		img: "",
	},
	{
		id: 7,
		name: "Logitech G Pro X Keyboard",
		desc: "Mechanical gaming keyboard with hot-swappable switches and compact design.",
		price: 129.99,
		stock: 40,
		category: "peripherals",
		img: "",
	},
	{
		id: 8,
		name: "Razer DeathAdder V3 Mouse",
		desc: "Lightweight ergonomic gaming mouse with Focus Pro 30K optical sensor.",
		price: 79.99,
		stock: 60,
		category: "peripherals",
		img: "",
	},
	{
		id: 9,
		name: "SteelSeries Arctis Nova 7 Headset",
		desc: "Wireless gaming headset with 360° spatial audio and long battery life.",
		price: 179.99,
		stock: 20,
		category: "peripherals",
		img: "",
	},
	{
		id: 10,
		name: "Glorious XL Mouse Pad",
		desc: "Large, smooth-surface mouse pad designed for low-friction gaming.",
		price: 29.99,
		stock: 80,
		category: "accessories",
		img: "",
	},
	{
		id: 11,
		name: "Elgato Stream Deck MK.2",
		desc: "Customizable control pad for streaming and productivity shortcuts.",
		price: 149.99,
		stock: 18,
		category: "accessories",
		img: "",
	},
	{
		id: 12,
		name: "CableMod Custom Cable Kit",
		desc: "Premium sleeved cables for a clean, aesthetic PC build.",
		price: 69.99,
		stock: 25,
		category: "accessories",
		img: "",
	},
	{
		id: 13,
		name: "Secretlab Titan Evo 2022 Chair",
		desc: "Ergonomic gaming chair with adjustable lumbar support and cold-cure foam.",
		price: 579.99,
		stock: 9,
		category: "chairs",
		img: "",
	},
	{
		id: 14,
		name: "Herman Miller x Logitech G Embody Chair",
		desc: "Premium ergonomic chair designed for long gaming and work sessions.",
		price: 1595.0,
		stock: 5,
		category: "chairs",
		img: "",
	},
	{
		id: 15,
		name: "Autonomous SmartDesk Pro",
		desc: "Adjustable standing desk with dual-motor lift and programmable presets.",
		price: 499.99,
		stock: 14,
		category: "desks",
		img: "",
	},
	{
		id: 16,
		name: "FlexiSpot E7 Standing Desk",
		desc: "Electric height-adjustable desk with solid steel frame and cable management.",
		price: 449.99,
		stock: 20,
		category: "desks",
		img: "",
	},
	{
		id: 17,
		name: "Cooler Master Hyper 212 Black Edition",
		desc: "Reliable air CPU cooler with quiet operation and sleek black finish.",
		price: 49.99,
		stock: 35,
		category: "parts",
		img: "",
	},
	{
		id: 18,
		name: "ASUS ROG Thor 850W PSU",
		desc: "Platinum-rated power supply with OLED display and Aura Sync RGB lighting.",
		price: 249.99,
		stock: 10,
		category: "parts",
		img: "",
	},
	{
		id: 19,
		name: "Logitech MX Master 3S",
		desc: "Ergonomic productivity mouse with MagSpeed scroll wheel and quiet clicks.",
		price: 99.99,
		stock: 40,
		category: "peripherals",
		img: "",
	},
	{
		id: 20,
		name: "Satechi USB-C Hub Pro",
		desc: "Aluminum hub with HDMI, USB-A, SD, and Ethernet ports for laptops.",
		price: 89.99,
		stock: 50,
		category: "accessories",
		img: "",
	},
];

function getItems({ category }: Filters): Article[] {
	return data.filter((item) => !category || item.category == category);
}

function getAllItems(): Article[] {
	return data;
}

export { getItems, getAllItems };
